"""initial schema

Revision ID: 9f1f74f4c202
Revises: 
Create Date: 2026-08-03 23:43:31.734628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1f74f4c202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layaways', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('product_colors_color_id_fkey'), 'product_colors', type_='foreignkey')
    op.drop_constraint(op.f('product_colors_product_id_fkey'), 'product_colors', type_='foreignkey')
    op.create_foreign_key(None, 'product_colors', 'colors', ['color_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_colors', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'product_colors', type_='foreignkey')
    op.drop_constraint(None, 'product_colors', type_='foreignkey')
    op.create_foreign_key(op.f('product_colors_product_id_fkey'), 'product_colors', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_colors_color_id_fkey'), 'product_colors', 'colors', ['color_id'], ['id'])
    op.alter_column('layaways', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
